### ISSUE TITLE
progress not work

### ISSUE THREAD

**Issue by changningtsai** [karlicoss/kobuddy#10]
2020-06-28 19:08:18 - kobuddy - ERROR - unexpected event: ??? by 865349ec-a40c-4961-b668-70d36b756f1e OrderedDict([('EventType', 64), ('EventCount', 2), ('LastOccurrence', '2019-05-30T09:46:12.242'), ('ContentID', '865349ec-a40c-4961-b668-70d36b756f1e'), ('Checksum', '7a14b9000df85e3504ebb4a16faa8175'), ('hex(ExtraData)', '000000030000003400450078007400720061004400610074006100530079006E00630065006400540069006D00650045006C006100700073006500640000000A000000000200300000002800450078007400720061004400610074006100530079006E0063006500640043006F0075006E00740000000200000000020000002E00450078007400720061004400610074006100520065006100640069006E0067005300650063006F006E006400730000000A00000000020030')])
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__main__.py", line 56, in <module>
    main()
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__main__.py", line 46, in main
    print_progress(errors=args.errors)
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 976, in print_progress
    for bevents in get_books_with_events(**kwargs):
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 968, in get_books_with_events
    vit = sorted(vit, key=lambda be: be.last)
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/common.py", line 62, in it_val
    for r in vit:
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 959, in iter_books_with_events
    for book, events in group_by_key(vit, key=lambda e: e.book).items():
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/common.py", line 37, in group_by_key
    for i in l:
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/common.py", line 62, in it_val
    for r in vit:
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 872, in iter_events
    for x in _iter_events_aux(**kwargs):
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 538, in _iter_events_aux
    raise e
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 535, in _iter_events_aux
    yield from _iter_events_aux_Event(row=row, books=books, idx=i)
  File "/mnt/d/eBooks/KoboTools/kobuddy/src/kobuddy/__init__.py", line 596, in _iter_events_aux_Event
    raise RuntimeError(str(row))
RuntimeError: OrderedDict([('EventType', 64), ('EventCount', 2), ('LastOccurrence', '2019-05-30T09:46:12.242'), ('ContentID', '865349ec-a40c-4961-b668-70d36b756f1e'), ('Checksum', '7a14b9000df85e3504ebb4a16faa8175'), ('hex(ExtraData)', '000000030000003400450078007400720061004400610074006100530079006E00630065006400540069006D00650045006C006100700073006500640000000A000000000200300000002800450078007400720061004400610074006100530079006E0063006500640043006F0075006E00740000000200000000020000002E00450078007400720061004400610074006100520065006100640069006E0067005300650063006F006E006400730000000A00000000020030')])

**Comment by rebpdx** [comment]
I had this same issue and found some more info in the [mobile reads forums about the binary data](https://www.mobileread.com/forums/showthread.php?t=313990).

It looks like some of the Kobo readers have some more values:

- `Orientation` which can have `Portrait` or `Landscape`
- `ButtonPressCount` which I think is the number of times the page turn buttons are used

I hacked this together in the lengths structure and was able to make it through my progress data without exceptions:

```python
lengths = {
        b'Orientation'               : 5,
        b'Portrait'                  : 0,
        b'Landscape'                 : 0,
        b'ButtonPressCount'          : 9,
```

It's a bit wonky just consuming the `Portrait` and `Landscape` as zero, since that's part of the `Orientation` data, but does work. I'm happy to make a PR of this or some other suggestion if you want to support more readers. (For reference I'm using a Kobo Libra H20)

**Comment by UlisseMini** [comment]
I had the same issue and I'm using @rebpdx's solution in my fork, I think this should get fixed with the hack unless we need the data (which seems unlikely, I can't think of a use for orientation data)

**Comment by karlicoss** [comment]
Sorry just noticed this somehow! 
Thanks for the suggested the fix, I merged it now! Better late then never :) 
Feel free to reopen if it's still not working somehow
