### ISSUE TITLE
AssertionError: assert book is not None

### ISSUE THREAD

**Issue by curiositry** [karlicoss/kobuddy#18]
Hello @karlicoss !

When I run kobuddy, I get:

```
Using /tmp/tmphnubcetl for highlights
Traceback (most recent call last):
  File "/home/username/.local/bin/kobuddy", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.8/site-packages/kobuddy/__main__.py", line 66, in main
    print_annotations()
  File "/home/username/.local/lib/python3.8/site-packages/kobuddy/__init__.py", line 989, in print_annotations
    for i in get_highlights():
  File "/home/username/.local/lib/python3.8/site-packages/kobuddy/__init__.py", line 854, in get_highlights
    return list(sorted(_iter_highlights(**kwargs), key=lambda h: h.created))
  File "/home/username/.local/lib/python3.8/site-packages/kobuddy/__init__.py", line 835, in _iter_highlights
    for h in _load_highlights(bfile, books=books):
  File "/home/username/.local/lib/python3.8/site-packages/kobuddy/__init__.py", line 848, in _load_highlights
    assert book is not None
AssertionError

```

I have tried it with the `--db` flag pointing to a backup of my KoboReader.sqlite, as well as letting it find my connected reader. I have tried it withr with progress and annotations with the same results.

I am using pip3 install of kobuddy (fresh install today) on Ubuntu, trying to export annotations from a Kobo Aura One with the latest firmware.

What am I doing wrong?

Thanks!

**Comment by karlicoss** [comment]
Hi! 
I actually noticed the PyPi version hasn't been updated for a while, so I released a new one. I don't think it would help with your error, but I added a bit more logging, so now when assert is triggered, you would get the bookmark it's failed on. 
Can you retry with the updated version and post the bookmark information here?

**Comment by curiositry** [comment]
Thank you!!

It seems to be failing on certain bookmarks (Type "dogear") — at least some (and possibly all) of which are for books that have been removed from the device storage. Example output:

```
2022-10-21 17:10:28 - kobuddy - INFO - Using /path/to/KoboReader.sqlite for highlights
Traceback (most recent call last):
  File "/path/to/kobuddy", line 8, in <module>
    sys.exit(main())
  File "/path/to/kobuddy/__main__.py", line 67, in main
    print_annotations()
  File "/path/to/kobuddy/__init__.py", line 1001, in print_annotations
    for i in get_highlights():
  File "/path/to/kobuddy/__init__.py", line 866, in get_highlights
    return list(sorted(_iter_highlights(**kwargs), key=lambda h: h.created))
  File "/path/to/kobuddy/__init__.py", line 847, in _iter_highlights
    for h in _load_highlights(bfile, books=books):
  File "/path/to/kobuddy/__init__.py", line 860, in _load_highlights
    assert book is not None, bm
AssertionError: OrderedDict([('BookmarkID', '[redated]'), ('VolumeID', '[redated]'), ('ContentID', '{[redated]}'), ('StartContainerPath', '#66'), ('StartContainerChildIndex', 0), ('StartOffset', 0), ('EndContainerPath', '#66'), ('EndContainerChildIndex', 0), ('EndOffset', 0), ('Text', None), ('Annotation', None), ('ExtraAnnotationData', None), ('DateCreated', '2019-12-04T04:47:22.465'), ('ChapterProgress', 0.795180722891566), ('Hidden', 'false'), ('Version', None), ('DateModified', '2019-12-04T04:47:22Z'), ('Creator', None), ('UUID', '[redated]'), ('UserID', '[redated]'), ('SyncTime', None), ('Published', 'false'), ('ContextString', None), ('Type', 'dogear')])

```

When I delete those entries manually, it works fine.

**Comment by karlicoss** [comment]
Thanks for sharing! I also have `dogear` bookmarks, but none of them are dangling, so I assume it just could be some difference between kobo devices or whatever. 
I added a workaround and released on pypi, I think it shouldn't crash anymore, and will create a 'fake' book that holds the orhpaned annotations. See more here: https://github.com/karlicoss/kobuddy/releases/tag/v0.2.20221023

If it works for you, feel free to close the issue -- and thanks for reporting by the way :)

**Comment by curiositry** [comment]
Thanks so much! That fixed it.
