### ISSUE TITLE
Progress functions fails. 

### ISSUE THREAD

**Issue by rigogsilva** [karlicoss/kobuddy#8]
Hi, trying to use your library. Getting this error when running `progress`. I am definitely interested in that `ExtraData` blob. I would be willing to get some work on that if I can get this one working. 

Thoughts?

```bash
(base) XXX:kobuddy-master rigo$ ./kobuddy --db KoboReader.sqlite progress 
2020-05-13 16:01:39 - kobuddy - INFO - Using KoboReader.sqlite for highlights
2020-05-13 16:01:39 - kobuddy - INFO - processing KoboReader.sqlite
Traceback (most recent call last):
  File "XXX:/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "XXX:/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__main__.py", line 56, in <module>
    main()
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__main__.py", line 46, in main
    print_progress(errors=args.errors)
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 968, in print_progress
    for bevents in get_books_with_events(**kwargs):
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 960, in get_books_with_events
    vit = sorted(vit, key=lambda be: be.last)
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/common.py", line 62, in it_val
    for r in vit:
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 951, in iter_books_with_events
    for book, events in group_by_key(vit, key=lambda e: e.book).items():
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/common.py", line 37, in group_by_key
    for i in l:
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/common.py", line 62, in it_val
    for r in vit:
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 864, in iter_events
    for x in _iter_events_aux(**kwargs):
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 530, in _iter_events_aux
    raise e
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 527, in _iter_events_aux
    yield from _iter_events_aux_Event(row=row, books=books, idx=i)
  File "XXX:/Documents/Projects/kobuddy-master/src/kobuddy/__init__.py", line 657, in _iter_events_aux_Event
    raise RuntimeError(f'Unexpected event kind: {name}\n' + context())
RuntimeError: Unexpected event kind: b'Orientation'

```

**Comment by karlicoss** [comment]
I can't test but this hopefully is fixed with https://github.com/karlicoss/kobuddy/pull/37
